"""empty message

Revision ID: 102948a600ff
Revises: 
Create Date: 2026-03-12 21:02:53.713730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102948a600ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('is_hr', sa.Boolean(), nullable=True),
    sa.Column('dept_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('hr_reviews',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('is_rejection', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('questions',
    sa.Column('q_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('q_content', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_table('answers',
    sa.Column('a_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('a_content', sa.Text(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['q_id'], ['questions.q_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_table('feedbacks',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('revised_score', sa.Integer(), nullable=True),
    sa.Column('mgr_comment', sa.Text(), nullable=True),
    sa.Column('hr_comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['a_id'], ['answers.a_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('hr_reviews')
    op.drop_table('users')
    # ### end Alembic commands ###
