"""Add summaries table

Revision ID: 22bc17cf6398
Revises: 102948a600ff
Create Date: 2026-03-15 01:13:56.127330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bc17cf6398'
down_revision = '102948a600ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['q_id'], ['questions.q_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    # ### end Alembic commands ###
